// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package eks provides the client and types for making API
// requests to A beautiful and amazing AWSWesleyFrontend.
//
// See https://docs.aws.amazon.com/goto/WebAPI/wesley-2017-07-25 for more information on this service.
//
// See eks package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/eks/
//
// Using the Client
//
// To contact A beautiful and amazing AWSWesleyFrontend with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the A beautiful and amazing AWSWesleyFrontend client EKS for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/eks/#New
package eks
